module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'users',
    ADMIN_COLLECTION:'admin',
    CATEGORY_COLLECTION:'category',
    INVENTORY_COLLECTION:'inventory',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    COUPON_COLLECTION:'coupon'
}